### ISSUE TITLE
Fails to build for Android

### ISSUE THREAD

**Issue by grischoun** [victir/ng2-cable-ionic2-example#1]
Hi,

I was trying your ng2-cable-ionic2-example and it works fine with:
ionic serve

But I get the error below when trying to run an android emulator (ionic emulate android).
Here is more info about my config:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002

[22:51:47]  Error: Error at 
            /Users/chrislain/workspace/IONIC/ng2-cable-ionic2-example/.tmp/app/app.module.ngfactory.ts:398:72 
[22:51:47]  Supplied parameters do not match any signature of call target. 
[22:51:47]  ngc failed 
[22:51:47]  ionic-app-script task: "build" 
[22:51:47]  Error: Error 

npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/chrislain/.nvm/versions/node/v7.2.1/bin/node" "/Users/chrislain/.nvm/versions/node/v7.2.1/bin/npm" "run" "ionic:build" "--"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.5

**Comment by viktor-shmigol** [comment]
@grischoun I have done it
